// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtHChwfSRChp6wADjvMJ5H77GSIpklkvY',
    appId: '1:472692266308:web:6656a4dd546ede5e9f7311',
    messagingSenderId: '472692266308',
    projectId: 'fir-student-a45e2',
    authDomain: 'fir-student-a45e2.firebaseapp.com',
    storageBucket: 'fir-student-a45e2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFYqM7jH0ztpaNhOBaliy1ntovfeyyUOU',
    appId: '1:472692266308:android:11d5ec9491a0d0c19f7311',
    messagingSenderId: '472692266308',
    projectId: 'fir-student-a45e2',
    storageBucket: 'fir-student-a45e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASlhefHU2eHjezwyu07rXBWtdILXuYVtk',
    appId: '1:472692266308:ios:c32cb42c1d8d1a9b9f7311',
    messagingSenderId: '472692266308',
    projectId: 'fir-student-a45e2',
    storageBucket: 'fir-student-a45e2.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASlhefHU2eHjezwyu07rXBWtdILXuYVtk',
    appId: '1:472692266308:ios:c32cb42c1d8d1a9b9f7311',
    messagingSenderId: '472692266308',
    projectId: 'fir-student-a45e2',
    storageBucket: 'fir-student-a45e2.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtHChwfSRChp6wADjvMJ5H77GSIpklkvY',
    appId: '1:472692266308:web:6fcb86d014485d3d9f7311',
    messagingSenderId: '472692266308',
    projectId: 'fir-student-a45e2',
    authDomain: 'fir-student-a45e2.firebaseapp.com',
    storageBucket: 'fir-student-a45e2.firebasestorage.app',
  );

}